version: '3.8'

services:
  iran-stock-analyzer:
    build: .
    container_name: iran-stock-analyzer
    environment:
      - BRS_API_KEY=${BRS_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: iran-stock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
